// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TSLIOTBusinessLog.proto

package com.terminus.iotextension.mqtt.protobuf;

public final class TSLIOTBusinessLog {
  private TSLIOTBusinessLog() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TSLIOTUploadPassLogRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TslIotProto.TSLIOTUploadPassLogRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 开门日志
     * </pre>
     *
     * <code>repeated .TslIotProto.TSLIOTUploadPassLogRequest.TSLIOTPassLog pass_logs = 1;</code>
     */
    java.util.List<TSLIOTUploadPassLogRequest.TSLIOTPassLog>
        getPassLogsList();
    /**
     * <pre>
     * 开门日志
     * </pre>
     *
     * <code>repeated .TslIotProto.TSLIOTUploadPassLogRequest.TSLIOTPassLog pass_logs = 1;</code>
     */
    TSLIOTUploadPassLogRequest.TSLIOTPassLog getPassLogs(int index);
    /**
     * <pre>
     * 开门日志
     * </pre>
     *
     * <code>repeated .TslIotProto.TSLIOTUploadPassLogRequest.TSLIOTPassLog pass_logs = 1;</code>
     */
    int getPassLogsCount();
    /**
     * <pre>
     * 开门日志
     * </pre>
     *
     * <code>repeated .TslIotProto.TSLIOTUploadPassLogRequest.TSLIOTPassLog pass_logs = 1;</code>
     */
    java.util.List<? extends TSLIOTUploadPassLogRequest.TSLIOTPassLogOrBuilder>
        getPassLogsOrBuilderList();
    /**
     * <pre>
     * 开门日志
     * </pre>
     *
     * <code>repeated .TslIotProto.TSLIOTUploadPassLogRequest.TSLIOTPassLog pass_logs = 1;</code>
     */
    TSLIOTUploadPassLogRequest.TSLIOTPassLogOrBuilder getPassLogsOrBuilder(
            int index);
  }
  /**
   * <pre>
   * 通行日志
   * </pre>
   *
   * Protobuf type {@code TslIotProto.TSLIOTUploadPassLogRequest}
   */
  public  static final class TSLIOTUploadPassLogRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:TslIotProto.TSLIOTUploadPassLogRequest)
      TSLIOTUploadPassLogRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TSLIOTUploadPassLogRequest.newBuilder() to construct.
    private TSLIOTUploadPassLogRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TSLIOTUploadPassLogRequest() {
      passLogs_ = java.util.Collections.emptyList();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TSLIOTUploadPassLogRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                passLogs_ = new java.util.ArrayList<TSLIOTPassLog>();
                mutable_bitField0_ |= 0x00000001;
              }
              passLogs_.add(
                  input.readMessage(TSLIOTPassLog.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          passLogs_ = java.util.Collections.unmodifiableList(passLogs_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return TSLIOTBusinessLog.internal_static_TslIotProto_TSLIOTUploadPassLogRequest_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return TSLIOTBusinessLog.internal_static_TslIotProto_TSLIOTUploadPassLogRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              TSLIOTUploadPassLogRequest.class, Builder.class);
    }

    public interface TSLIOTPassLogOrBuilder extends
        // @@protoc_insertion_point(interface_extends:TslIotProto.TSLIOTUploadPassLogRequest.TSLIOTPassLog)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <pre>
       * 设备id
       * </pre>
       *
       * <code>string dev_id = 1;</code>
       */
      String getDevId();
      /**
       * <pre>
       * 设备id
       * </pre>
       *
       * <code>string dev_id = 1;</code>
       */
      com.google.protobuf.ByteString
          getDevIdBytes();

      /**
       * <pre>
       * 用户id, 当是陌生人时 ，这个值为 -1
       * </pre>
       *
       * <code>int64 person_id = 2;</code>
       */
      long getPersonId();

      /**
       * <pre>
       * 人员特征描述 用 json描述 // 男女，头发长短，年龄估计，等
       * </pre>
       *
       * <code>string feature = 3;</code>
       */
      String getFeature();
      /**
       * <pre>
       * 人员特征描述 用 json描述 // 男女，头发长短，年龄估计，等
       * </pre>
       *
       * <code>string feature = 3;</code>
       */
      com.google.protobuf.ByteString
          getFeatureBytes();

      /**
       * <pre>
       * 人员类型："user":用户 "black":黑名单（报警）"visitor"：访客 "unknown":陌生人
       * </pre>
       *
       * <code>string person_type = 4;</code>
       */
      String getPersonType();
      /**
       * <pre>
       * 人员类型："user":用户 "black":黑名单（报警）"visitor"：访客 "unknown":陌生人
       * </pre>
       *
       * <code>string person_type = 4;</code>
       */
      com.google.protobuf.ByteString
          getPersonTypeBytes();

      /**
       * <pre>
       * 进出方向，0:未知，1:进   2:出
       * </pre>
       *
       * <code>int32 direction = 5;</code>
       */
      int getDirection();

      /**
       * <pre>
       * 开门时间 ms
       * </pre>
       *
       * <code>int64 time = 6;</code>
       */
      long getTime();

      /**
       * <pre>
       * 成功：0，失败：1,  2:无效二维码（TOTP失败,BASE64解码失败,AES解码失败） , 3:无效用户(phone不存在，phone过期)
       * </pre>
       *
       * <code>int32 open_result = 7;</code>
       */
      int getOpenResult();

      /**
       * <pre>
       * 设备状态：0: 关闭，1: 开启, 2: 异常，etc.
       * </pre>
       *
       * <code>int32 dev_status = 8;</code>
       */
      int getDevStatus();

      /**
       * <pre>
       * 开门方式: 0-刷卡, 1-一次性密码，2-app远程开门，3-门内开门（按键开门），
       * </pre>
       *
       * <code>int32 open_type = 9;</code>
       */
      int getOpenType();

      /**
       * <pre>
       * 4-人脸识别开门，5-指纹识别开门, 6-普通密码开门, 7-DTMF开门, 8-app蓝牙开门（由APP上报，设备不用上报）, 9-二维码开门
       * </pre>
       *
       * <code>string card_no = 10;</code>
       */
      String getCardNo();
      /**
       * <pre>
       * 4-人脸识别开门，5-指纹识别开门, 6-普通密码开门, 7-DTMF开门, 8-app蓝牙开门（由APP上报，设备不用上报）, 9-二维码开门
       * </pre>
       *
       * <code>string card_no = 10;</code>
       */
      com.google.protobuf.ByteString
          getCardNoBytes();

      /**
       * <pre>
       * 通行图片url, 多个图片路径 用;分割  （如果是两张图：头像图在前，整个截图大图在后）
       * </pre>
       *
       * <code>string pass_img = 11;</code>
       */
      String getPassImg();
      /**
       * <pre>
       * 通行图片url, 多个图片路径 用;分割  （如果是两张图：头像图在前，整个截图大图在后）
       * </pre>
       *
       * <code>string pass_img = 11;</code>
       */
      com.google.protobuf.ByteString
          getPassImgBytes();

      /**
       * <pre>
       * 通行视频url
       * </pre>
       *
       * <code>string pass_video = 12;</code>
       */
      String getPassVideo();
      /**
       * <pre>
       * 通行视频url
       * </pre>
       *
       * <code>string pass_video = 12;</code>
       */
      com.google.protobuf.ByteString
          getPassVideoBytes();

      /**
       * <pre>
       * 预留字段，用于存储通行记录的特定信息 JsonString  例如二维码通行时带有二维码特定自定义信息 {"qrCustomInfo":"xxxx"}
       * </pre>
       *
       * <code>string reserve = 13;</code>
       */
      String getReserve();
      /**
       * <pre>
       * 预留字段，用于存储通行记录的特定信息 JsonString  例如二维码通行时带有二维码特定自定义信息 {"qrCustomInfo":"xxxx"}
       * </pre>
       *
       * <code>string reserve = 13;</code>
       */
      com.google.protobuf.ByteString
          getReserveBytes();
    }
    /**
     * Protobuf type {@code TslIotProto.TSLIOTUploadPassLogRequest.TSLIOTPassLog}
     */
    public  static final class TSLIOTPassLog extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:TslIotProto.TSLIOTUploadPassLogRequest.TSLIOTPassLog)
        TSLIOTPassLogOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use TSLIOTPassLog.newBuilder() to construct.
      private TSLIOTPassLog(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private TSLIOTPassLog() {
        devId_ = "";
        personId_ = 0L;
        feature_ = "";
        personType_ = "";
        direction_ = 0;
        time_ = 0L;
        openResult_ = 0;
        devStatus_ = 0;
        openType_ = 0;
        cardNo_ = "";
        passImg_ = "";
        passVideo_ = "";
        reserve_ = "";
      }

      @Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private TSLIOTPassLog(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownFieldProto3(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                String s = input.readStringRequireUtf8();

                devId_ = s;
                break;
              }
              case 16: {

                personId_ = input.readInt64();
                break;
              }
              case 26: {
                String s = input.readStringRequireUtf8();

                feature_ = s;
                break;
              }
              case 34: {
                String s = input.readStringRequireUtf8();

                personType_ = s;
                break;
              }
              case 40: {

                direction_ = input.readInt32();
                break;
              }
              case 48: {

                time_ = input.readInt64();
                break;
              }
              case 56: {

                openResult_ = input.readInt32();
                break;
              }
              case 64: {

                devStatus_ = input.readInt32();
                break;
              }
              case 72: {

                openType_ = input.readInt32();
                break;
              }
              case 82: {
                String s = input.readStringRequireUtf8();

                cardNo_ = s;
                break;
              }
              case 90: {
                String s = input.readStringRequireUtf8();

                passImg_ = s;
                break;
              }
              case 98: {
                String s = input.readStringRequireUtf8();

                passVideo_ = s;
                break;
              }
              case 106: {
                String s = input.readStringRequireUtf8();

                reserve_ = s;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return TSLIOTBusinessLog.internal_static_TslIotProto_TSLIOTUploadPassLogRequest_TSLIOTPassLog_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return TSLIOTBusinessLog.internal_static_TslIotProto_TSLIOTUploadPassLogRequest_TSLIOTPassLog_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                TSLIOTPassLog.class, Builder.class);
      }

      public static final int DEV_ID_FIELD_NUMBER = 1;
      private volatile Object devId_;
      /**
       * <pre>
       * 设备id
       * </pre>
       *
       * <code>string dev_id = 1;</code>
       */
      public String getDevId() {
        Object ref = devId_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          devId_ = s;
          return s;
        }
      }
      /**
       * <pre>
       * 设备id
       * </pre>
       *
       * <code>string dev_id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getDevIdBytes() {
        Object ref = devId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          devId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int PERSON_ID_FIELD_NUMBER = 2;
      private long personId_;
      /**
       * <pre>
       * 用户id, 当是陌生人时 ，这个值为 -1
       * </pre>
       *
       * <code>int64 person_id = 2;</code>
       */
      public long getPersonId() {
        return personId_;
      }

      public static final int FEATURE_FIELD_NUMBER = 3;
      private volatile Object feature_;
      /**
       * <pre>
       * 人员特征描述 用 json描述 // 男女，头发长短，年龄估计，等
       * </pre>
       *
       * <code>string feature = 3;</code>
       */
      public String getFeature() {
        Object ref = feature_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          feature_ = s;
          return s;
        }
      }
      /**
       * <pre>
       * 人员特征描述 用 json描述 // 男女，头发长短，年龄估计，等
       * </pre>
       *
       * <code>string feature = 3;</code>
       */
      public com.google.protobuf.ByteString
          getFeatureBytes() {
        Object ref = feature_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          feature_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int PERSON_TYPE_FIELD_NUMBER = 4;
      private volatile Object personType_;
      /**
       * <pre>
       * 人员类型："user":用户 "black":黑名单（报警）"visitor"：访客 "unknown":陌生人
       * </pre>
       *
       * <code>string person_type = 4;</code>
       */
      public String getPersonType() {
        Object ref = personType_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          personType_ = s;
          return s;
        }
      }
      /**
       * <pre>
       * 人员类型："user":用户 "black":黑名单（报警）"visitor"：访客 "unknown":陌生人
       * </pre>
       *
       * <code>string person_type = 4;</code>
       */
      public com.google.protobuf.ByteString
          getPersonTypeBytes() {
        Object ref = personType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          personType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int DIRECTION_FIELD_NUMBER = 5;
      private int direction_;
      /**
       * <pre>
       * 进出方向，0:未知，1:进   2:出
       * </pre>
       *
       * <code>int32 direction = 5;</code>
       */
      public int getDirection() {
        return direction_;
      }

      public static final int TIME_FIELD_NUMBER = 6;
      private long time_;
      /**
       * <pre>
       * 开门时间 ms
       * </pre>
       *
       * <code>int64 time = 6;</code>
       */
      public long getTime() {
        return time_;
      }

      public static final int OPEN_RESULT_FIELD_NUMBER = 7;
      private int openResult_;
      /**
       * <pre>
       * 成功：0，失败：1,  2:无效二维码（TOTP失败,BASE64解码失败,AES解码失败） , 3:无效用户(phone不存在，phone过期)
       * </pre>
       *
       * <code>int32 open_result = 7;</code>
       */
      public int getOpenResult() {
        return openResult_;
      }

      public static final int DEV_STATUS_FIELD_NUMBER = 8;
      private int devStatus_;
      /**
       * <pre>
       * 设备状态：0: 关闭，1: 开启, 2: 异常，etc.
       * </pre>
       *
       * <code>int32 dev_status = 8;</code>
       */
      public int getDevStatus() {
        return devStatus_;
      }

      public static final int OPEN_TYPE_FIELD_NUMBER = 9;
      private int openType_;
      /**
       * <pre>
       * 开门方式: 0-刷卡, 1-一次性密码，2-app远程开门，3-门内开门（按键开门），
       * </pre>
       *
       * <code>int32 open_type = 9;</code>
       */
      public int getOpenType() {
        return openType_;
      }

      public static final int CARD_NO_FIELD_NUMBER = 10;
      private volatile Object cardNo_;
      /**
       * <pre>
       * 4-人脸识别开门，5-指纹识别开门, 6-普通密码开门, 7-DTMF开门, 8-app蓝牙开门（由APP上报，设备不用上报）, 9-二维码开门
       * </pre>
       *
       * <code>string card_no = 10;</code>
       */
      public String getCardNo() {
        Object ref = cardNo_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          cardNo_ = s;
          return s;
        }
      }
      /**
       * <pre>
       * 4-人脸识别开门，5-指纹识别开门, 6-普通密码开门, 7-DTMF开门, 8-app蓝牙开门（由APP上报，设备不用上报）, 9-二维码开门
       * </pre>
       *
       * <code>string card_no = 10;</code>
       */
      public com.google.protobuf.ByteString
          getCardNoBytes() {
        Object ref = cardNo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          cardNo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int PASS_IMG_FIELD_NUMBER = 11;
      private volatile Object passImg_;
      /**
       * <pre>
       * 通行图片url, 多个图片路径 用;分割  （如果是两张图：头像图在前，整个截图大图在后）
       * </pre>
       *
       * <code>string pass_img = 11;</code>
       */
      public String getPassImg() {
        Object ref = passImg_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          passImg_ = s;
          return s;
        }
      }
      /**
       * <pre>
       * 通行图片url, 多个图片路径 用;分割  （如果是两张图：头像图在前，整个截图大图在后）
       * </pre>
       *
       * <code>string pass_img = 11;</code>
       */
      public com.google.protobuf.ByteString
          getPassImgBytes() {
        Object ref = passImg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          passImg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int PASS_VIDEO_FIELD_NUMBER = 12;
      private volatile Object passVideo_;
      /**
       * <pre>
       * 通行视频url
       * </pre>
       *
       * <code>string pass_video = 12;</code>
       */
      public String getPassVideo() {
        Object ref = passVideo_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          passVideo_ = s;
          return s;
        }
      }
      /**
       * <pre>
       * 通行视频url
       * </pre>
       *
       * <code>string pass_video = 12;</code>
       */
      public com.google.protobuf.ByteString
          getPassVideoBytes() {
        Object ref = passVideo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          passVideo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int RESERVE_FIELD_NUMBER = 13;
      private volatile Object reserve_;
      /**
       * <pre>
       * 预留字段，用于存储通行记录的特定信息 JsonString  例如二维码通行时带有二维码特定自定义信息 {"qrCustomInfo":"xxxx"}
       * </pre>
       *
       * <code>string reserve = 13;</code>
       */
      public String getReserve() {
        Object ref = reserve_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          reserve_ = s;
          return s;
        }
      }
      /**
       * <pre>
       * 预留字段，用于存储通行记录的特定信息 JsonString  例如二维码通行时带有二维码特定自定义信息 {"qrCustomInfo":"xxxx"}
       * </pre>
       *
       * <code>string reserve = 13;</code>
       */
      public com.google.protobuf.ByteString
          getReserveBytes() {
        Object ref = reserve_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          reserve_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!getDevIdBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, devId_);
        }
        if (personId_ != 0L) {
          output.writeInt64(2, personId_);
        }
        if (!getFeatureBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 3, feature_);
        }
        if (!getPersonTypeBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 4, personType_);
        }
        if (direction_ != 0) {
          output.writeInt32(5, direction_);
        }
        if (time_ != 0L) {
          output.writeInt64(6, time_);
        }
        if (openResult_ != 0) {
          output.writeInt32(7, openResult_);
        }
        if (devStatus_ != 0) {
          output.writeInt32(8, devStatus_);
        }
        if (openType_ != 0) {
          output.writeInt32(9, openType_);
        }
        if (!getCardNoBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 10, cardNo_);
        }
        if (!getPassImgBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 11, passImg_);
        }
        if (!getPassVideoBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 12, passVideo_);
        }
        if (!getReserveBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 13, reserve_);
        }
        unknownFields.writeTo(output);
      }

      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!getDevIdBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, devId_);
        }
        if (personId_ != 0L) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(2, personId_);
        }
        if (!getFeatureBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, feature_);
        }
        if (!getPersonTypeBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, personType_);
        }
        if (direction_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(5, direction_);
        }
        if (time_ != 0L) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(6, time_);
        }
        if (openResult_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(7, openResult_);
        }
        if (devStatus_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(8, devStatus_);
        }
        if (openType_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(9, openType_);
        }
        if (!getCardNoBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, cardNo_);
        }
        if (!getPassImgBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, passImg_);
        }
        if (!getPassVideoBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, passVideo_);
        }
        if (!getReserveBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, reserve_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @Override
      public boolean equals(final Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof TSLIOTPassLog)) {
          return super.equals(obj);
        }
        TSLIOTPassLog other = (TSLIOTPassLog) obj;

        boolean result = true;
        result = result && getDevId()
            .equals(other.getDevId());
        result = result && (getPersonId()
            == other.getPersonId());
        result = result && getFeature()
            .equals(other.getFeature());
        result = result && getPersonType()
            .equals(other.getPersonType());
        result = result && (getDirection()
            == other.getDirection());
        result = result && (getTime()
            == other.getTime());
        result = result && (getOpenResult()
            == other.getOpenResult());
        result = result && (getDevStatus()
            == other.getDevStatus());
        result = result && (getOpenType()
            == other.getOpenType());
        result = result && getCardNo()
            .equals(other.getCardNo());
        result = result && getPassImg()
            .equals(other.getPassImg());
        result = result && getPassVideo()
            .equals(other.getPassVideo());
        result = result && getReserve()
            .equals(other.getReserve());
        result = result && unknownFields.equals(other.unknownFields);
        return result;
      }

      @Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + DEV_ID_FIELD_NUMBER;
        hash = (53 * hash) + getDevId().hashCode();
        hash = (37 * hash) + PERSON_ID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getPersonId());
        hash = (37 * hash) + FEATURE_FIELD_NUMBER;
        hash = (53 * hash) + getFeature().hashCode();
        hash = (37 * hash) + PERSON_TYPE_FIELD_NUMBER;
        hash = (53 * hash) + getPersonType().hashCode();
        hash = (37 * hash) + DIRECTION_FIELD_NUMBER;
        hash = (53 * hash) + getDirection();
        hash = (37 * hash) + TIME_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getTime());
        hash = (37 * hash) + OPEN_RESULT_FIELD_NUMBER;
        hash = (53 * hash) + getOpenResult();
        hash = (37 * hash) + DEV_STATUS_FIELD_NUMBER;
        hash = (53 * hash) + getDevStatus();
        hash = (37 * hash) + OPEN_TYPE_FIELD_NUMBER;
        hash = (53 * hash) + getOpenType();
        hash = (37 * hash) + CARD_NO_FIELD_NUMBER;
        hash = (53 * hash) + getCardNo().hashCode();
        hash = (37 * hash) + PASS_IMG_FIELD_NUMBER;
        hash = (53 * hash) + getPassImg().hashCode();
        hash = (37 * hash) + PASS_VIDEO_FIELD_NUMBER;
        hash = (53 * hash) + getPassVideo().hashCode();
        hash = (37 * hash) + RESERVE_FIELD_NUMBER;
        hash = (53 * hash) + getReserve().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static TSLIOTPassLog parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static TSLIOTPassLog parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static TSLIOTPassLog parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static TSLIOTPassLog parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static TSLIOTPassLog parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static TSLIOTPassLog parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static TSLIOTPassLog parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static TSLIOTPassLog parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static TSLIOTPassLog parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static TSLIOTPassLog parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static TSLIOTPassLog parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static TSLIOTPassLog parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(TSLIOTPassLog prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @Override
      protected Builder newBuilderForType(
          BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code TslIotProto.TSLIOTUploadPassLogRequest.TSLIOTPassLog}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:TslIotProto.TSLIOTUploadPassLogRequest.TSLIOTPassLog)
          TSLIOTPassLogOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return TSLIOTBusinessLog.internal_static_TslIotProto_TSLIOTUploadPassLogRequest_TSLIOTPassLog_descriptor;
        }

        protected FieldAccessorTable
            internalGetFieldAccessorTable() {
          return TSLIOTBusinessLog.internal_static_TslIotProto_TSLIOTUploadPassLogRequest_TSLIOTPassLog_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  TSLIOTPassLog.class, Builder.class);
        }

        // Construct using com.terminus.iotextension.mqtt.protobuf.TSLIOTBusinessLog.TSLIOTUploadPassLogRequest.TSLIOTPassLog.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          devId_ = "";

          personId_ = 0L;

          feature_ = "";

          personType_ = "";

          direction_ = 0;

          time_ = 0L;

          openResult_ = 0;

          devStatus_ = 0;

          openType_ = 0;

          cardNo_ = "";

          passImg_ = "";

          passVideo_ = "";

          reserve_ = "";

          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return TSLIOTBusinessLog.internal_static_TslIotProto_TSLIOTUploadPassLogRequest_TSLIOTPassLog_descriptor;
        }

        public TSLIOTPassLog getDefaultInstanceForType() {
          return TSLIOTPassLog.getDefaultInstance();
        }

        public TSLIOTPassLog build() {
          TSLIOTPassLog result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public TSLIOTPassLog buildPartial() {
          TSLIOTPassLog result = new TSLIOTPassLog(this);
          result.devId_ = devId_;
          result.personId_ = personId_;
          result.feature_ = feature_;
          result.personType_ = personType_;
          result.direction_ = direction_;
          result.time_ = time_;
          result.openResult_ = openResult_;
          result.devStatus_ = devStatus_;
          result.openType_ = openType_;
          result.cardNo_ = cardNo_;
          result.passImg_ = passImg_;
          result.passVideo_ = passVideo_;
          result.reserve_ = reserve_;
          onBuilt();
          return result;
        }

        public Builder clone() {
          return (Builder) super.clone();
        }
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.setField(field, value);
        }
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof TSLIOTPassLog) {
            return mergeFrom((TSLIOTPassLog)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(TSLIOTPassLog other) {
          if (other == TSLIOTPassLog.getDefaultInstance()) return this;
          if (!other.getDevId().isEmpty()) {
            devId_ = other.devId_;
            onChanged();
          }
          if (other.getPersonId() != 0L) {
            setPersonId(other.getPersonId());
          }
          if (!other.getFeature().isEmpty()) {
            feature_ = other.feature_;
            onChanged();
          }
          if (!other.getPersonType().isEmpty()) {
            personType_ = other.personType_;
            onChanged();
          }
          if (other.getDirection() != 0) {
            setDirection(other.getDirection());
          }
          if (other.getTime() != 0L) {
            setTime(other.getTime());
          }
          if (other.getOpenResult() != 0) {
            setOpenResult(other.getOpenResult());
          }
          if (other.getDevStatus() != 0) {
            setDevStatus(other.getDevStatus());
          }
          if (other.getOpenType() != 0) {
            setOpenType(other.getOpenType());
          }
          if (!other.getCardNo().isEmpty()) {
            cardNo_ = other.cardNo_;
            onChanged();
          }
          if (!other.getPassImg().isEmpty()) {
            passImg_ = other.passImg_;
            onChanged();
          }
          if (!other.getPassVideo().isEmpty()) {
            passVideo_ = other.passVideo_;
            onChanged();
          }
          if (!other.getReserve().isEmpty()) {
            reserve_ = other.reserve_;
            onChanged();
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          TSLIOTPassLog parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (TSLIOTPassLog) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private Object devId_ = "";
        /**
         * <pre>
         * 设备id
         * </pre>
         *
         * <code>string dev_id = 1;</code>
         */
        public String getDevId() {
          Object ref = devId_;
          if (!(ref instanceof String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            devId_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        /**
         * <pre>
         * 设备id
         * </pre>
         *
         * <code>string dev_id = 1;</code>
         */
        public com.google.protobuf.ByteString
            getDevIdBytes() {
          Object ref = devId_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (String) ref);
            devId_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <pre>
         * 设备id
         * </pre>
         *
         * <code>string dev_id = 1;</code>
         */
        public Builder setDevId(
            String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          devId_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         * 设备id
         * </pre>
         *
         * <code>string dev_id = 1;</code>
         */
        public Builder clearDevId() {
          
          devId_ = getDefaultInstance().getDevId();
          onChanged();
          return this;
        }
        /**
         * <pre>
         * 设备id
         * </pre>
         *
         * <code>string dev_id = 1;</code>
         */
        public Builder setDevIdBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          devId_ = value;
          onChanged();
          return this;
        }

        private long personId_ ;
        /**
         * <pre>
         * 用户id, 当是陌生人时 ，这个值为 -1
         * </pre>
         *
         * <code>int64 person_id = 2;</code>
         */
        public long getPersonId() {
          return personId_;
        }
        /**
         * <pre>
         * 用户id, 当是陌生人时 ，这个值为 -1
         * </pre>
         *
         * <code>int64 person_id = 2;</code>
         */
        public Builder setPersonId(long value) {
          
          personId_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         * 用户id, 当是陌生人时 ，这个值为 -1
         * </pre>
         *
         * <code>int64 person_id = 2;</code>
         */
        public Builder clearPersonId() {
          
          personId_ = 0L;
          onChanged();
          return this;
        }

        private Object feature_ = "";
        /**
         * <pre>
         * 人员特征描述 用 json描述 // 男女，头发长短，年龄估计，等
         * </pre>
         *
         * <code>string feature = 3;</code>
         */
        public String getFeature() {
          Object ref = feature_;
          if (!(ref instanceof String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            feature_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        /**
         * <pre>
         * 人员特征描述 用 json描述 // 男女，头发长短，年龄估计，等
         * </pre>
         *
         * <code>string feature = 3;</code>
         */
        public com.google.protobuf.ByteString
            getFeatureBytes() {
          Object ref = feature_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (String) ref);
            feature_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <pre>
         * 人员特征描述 用 json描述 // 男女，头发长短，年龄估计，等
         * </pre>
         *
         * <code>string feature = 3;</code>
         */
        public Builder setFeature(
            String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          feature_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         * 人员特征描述 用 json描述 // 男女，头发长短，年龄估计，等
         * </pre>
         *
         * <code>string feature = 3;</code>
         */
        public Builder clearFeature() {
          
          feature_ = getDefaultInstance().getFeature();
          onChanged();
          return this;
        }
        /**
         * <pre>
         * 人员特征描述 用 json描述 // 男女，头发长短，年龄估计，等
         * </pre>
         *
         * <code>string feature = 3;</code>
         */
        public Builder setFeatureBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          feature_ = value;
          onChanged();
          return this;
        }

        private Object personType_ = "";
        /**
         * <pre>
         * 人员类型："user":用户 "black":黑名单（报警）"visitor"：访客 "unknown":陌生人
         * </pre>
         *
         * <code>string person_type = 4;</code>
         */
        public String getPersonType() {
          Object ref = personType_;
          if (!(ref instanceof String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            personType_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        /**
         * <pre>
         * 人员类型："user":用户 "black":黑名单（报警）"visitor"：访客 "unknown":陌生人
         * </pre>
         *
         * <code>string person_type = 4;</code>
         */
        public com.google.protobuf.ByteString
            getPersonTypeBytes() {
          Object ref = personType_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (String) ref);
            personType_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <pre>
         * 人员类型："user":用户 "black":黑名单（报警）"visitor"：访客 "unknown":陌生人
         * </pre>
         *
         * <code>string person_type = 4;</code>
         */
        public Builder setPersonType(
            String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          personType_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         * 人员类型："user":用户 "black":黑名单（报警）"visitor"：访客 "unknown":陌生人
         * </pre>
         *
         * <code>string person_type = 4;</code>
         */
        public Builder clearPersonType() {
          
          personType_ = getDefaultInstance().getPersonType();
          onChanged();
          return this;
        }
        /**
         * <pre>
         * 人员类型："user":用户 "black":黑名单（报警）"visitor"：访客 "unknown":陌生人
         * </pre>
         *
         * <code>string person_type = 4;</code>
         */
        public Builder setPersonTypeBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          personType_ = value;
          onChanged();
          return this;
        }

        private int direction_ ;
        /**
         * <pre>
         * 进出方向，0:未知，1:进   2:出
         * </pre>
         *
         * <code>int32 direction = 5;</code>
         */
        public int getDirection() {
          return direction_;
        }
        /**
         * <pre>
         * 进出方向，0:未知，1:进   2:出
         * </pre>
         *
         * <code>int32 direction = 5;</code>
         */
        public Builder setDirection(int value) {
          
          direction_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         * 进出方向，0:未知，1:进   2:出
         * </pre>
         *
         * <code>int32 direction = 5;</code>
         */
        public Builder clearDirection() {
          
          direction_ = 0;
          onChanged();
          return this;
        }

        private long time_ ;
        /**
         * <pre>
         * 开门时间 ms
         * </pre>
         *
         * <code>int64 time = 6;</code>
         */
        public long getTime() {
          return time_;
        }
        /**
         * <pre>
         * 开门时间 ms
         * </pre>
         *
         * <code>int64 time = 6;</code>
         */
        public Builder setTime(long value) {
          
          time_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         * 开门时间 ms
         * </pre>
         *
         * <code>int64 time = 6;</code>
         */
        public Builder clearTime() {
          
          time_ = 0L;
          onChanged();
          return this;
        }

        private int openResult_ ;
        /**
         * <pre>
         * 成功：0，失败：1,  2:无效二维码（TOTP失败,BASE64解码失败,AES解码失败） , 3:无效用户(phone不存在，phone过期)
         * </pre>
         *
         * <code>int32 open_result = 7;</code>
         */
        public int getOpenResult() {
          return openResult_;
        }
        /**
         * <pre>
         * 成功：0，失败：1,  2:无效二维码（TOTP失败,BASE64解码失败,AES解码失败） , 3:无效用户(phone不存在，phone过期)
         * </pre>
         *
         * <code>int32 open_result = 7;</code>
         */
        public Builder setOpenResult(int value) {
          
          openResult_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         * 成功：0，失败：1,  2:无效二维码（TOTP失败,BASE64解码失败,AES解码失败） , 3:无效用户(phone不存在，phone过期)
         * </pre>
         *
         * <code>int32 open_result = 7;</code>
         */
        public Builder clearOpenResult() {
          
          openResult_ = 0;
          onChanged();
          return this;
        }

        private int devStatus_ ;
        /**
         * <pre>
         * 设备状态：0: 关闭，1: 开启, 2: 异常，etc.
         * </pre>
         *
         * <code>int32 dev_status = 8;</code>
         */
        public int getDevStatus() {
          return devStatus_;
        }
        /**
         * <pre>
         * 设备状态：0: 关闭，1: 开启, 2: 异常，etc.
         * </pre>
         *
         * <code>int32 dev_status = 8;</code>
         */
        public Builder setDevStatus(int value) {
          
          devStatus_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         * 设备状态：0: 关闭，1: 开启, 2: 异常，etc.
         * </pre>
         *
         * <code>int32 dev_status = 8;</code>
         */
        public Builder clearDevStatus() {
          
          devStatus_ = 0;
          onChanged();
          return this;
        }

        private int openType_ ;
        /**
         * <pre>
         * 开门方式: 0-刷卡, 1-一次性密码，2-app远程开门，3-门内开门（按键开门），
         * </pre>
         *
         * <code>int32 open_type = 9;</code>
         */
        public int getOpenType() {
          return openType_;
        }
        /**
         * <pre>
         * 开门方式: 0-刷卡, 1-一次性密码，2-app远程开门，3-门内开门（按键开门），
         * </pre>
         *
         * <code>int32 open_type = 9;</code>
         */
        public Builder setOpenType(int value) {
          
          openType_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         * 开门方式: 0-刷卡, 1-一次性密码，2-app远程开门，3-门内开门（按键开门），
         * </pre>
         *
         * <code>int32 open_type = 9;</code>
         */
        public Builder clearOpenType() {
          
          openType_ = 0;
          onChanged();
          return this;
        }

        private Object cardNo_ = "";
        /**
         * <pre>
         * 4-人脸识别开门，5-指纹识别开门, 6-普通密码开门, 7-DTMF开门, 8-app蓝牙开门（由APP上报，设备不用上报）, 9-二维码开门
         * </pre>
         *
         * <code>string card_no = 10;</code>
         */
        public String getCardNo() {
          Object ref = cardNo_;
          if (!(ref instanceof String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            cardNo_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        /**
         * <pre>
         * 4-人脸识别开门，5-指纹识别开门, 6-普通密码开门, 7-DTMF开门, 8-app蓝牙开门（由APP上报，设备不用上报）, 9-二维码开门
         * </pre>
         *
         * <code>string card_no = 10;</code>
         */
        public com.google.protobuf.ByteString
            getCardNoBytes() {
          Object ref = cardNo_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (String) ref);
            cardNo_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <pre>
         * 4-人脸识别开门，5-指纹识别开门, 6-普通密码开门, 7-DTMF开门, 8-app蓝牙开门（由APP上报，设备不用上报）, 9-二维码开门
         * </pre>
         *
         * <code>string card_no = 10;</code>
         */
        public Builder setCardNo(
            String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          cardNo_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         * 4-人脸识别开门，5-指纹识别开门, 6-普通密码开门, 7-DTMF开门, 8-app蓝牙开门（由APP上报，设备不用上报）, 9-二维码开门
         * </pre>
         *
         * <code>string card_no = 10;</code>
         */
        public Builder clearCardNo() {
          
          cardNo_ = getDefaultInstance().getCardNo();
          onChanged();
          return this;
        }
        /**
         * <pre>
         * 4-人脸识别开门，5-指纹识别开门, 6-普通密码开门, 7-DTMF开门, 8-app蓝牙开门（由APP上报，设备不用上报）, 9-二维码开门
         * </pre>
         *
         * <code>string card_no = 10;</code>
         */
        public Builder setCardNoBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          cardNo_ = value;
          onChanged();
          return this;
        }

        private Object passImg_ = "";
        /**
         * <pre>
         * 通行图片url, 多个图片路径 用;分割  （如果是两张图：头像图在前，整个截图大图在后）
         * </pre>
         *
         * <code>string pass_img = 11;</code>
         */
        public String getPassImg() {
          Object ref = passImg_;
          if (!(ref instanceof String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            passImg_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        /**
         * <pre>
         * 通行图片url, 多个图片路径 用;分割  （如果是两张图：头像图在前，整个截图大图在后）
         * </pre>
         *
         * <code>string pass_img = 11;</code>
         */
        public com.google.protobuf.ByteString
            getPassImgBytes() {
          Object ref = passImg_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (String) ref);
            passImg_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <pre>
         * 通行图片url, 多个图片路径 用;分割  （如果是两张图：头像图在前，整个截图大图在后）
         * </pre>
         *
         * <code>string pass_img = 11;</code>
         */
        public Builder setPassImg(
            String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          passImg_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         * 通行图片url, 多个图片路径 用;分割  （如果是两张图：头像图在前，整个截图大图在后）
         * </pre>
         *
         * <code>string pass_img = 11;</code>
         */
        public Builder clearPassImg() {
          
          passImg_ = getDefaultInstance().getPassImg();
          onChanged();
          return this;
        }
        /**
         * <pre>
         * 通行图片url, 多个图片路径 用;分割  （如果是两张图：头像图在前，整个截图大图在后）
         * </pre>
         *
         * <code>string pass_img = 11;</code>
         */
        public Builder setPassImgBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          passImg_ = value;
          onChanged();
          return this;
        }

        private Object passVideo_ = "";
        /**
         * <pre>
         * 通行视频url
         * </pre>
         *
         * <code>string pass_video = 12;</code>
         */
        public String getPassVideo() {
          Object ref = passVideo_;
          if (!(ref instanceof String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            passVideo_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        /**
         * <pre>
         * 通行视频url
         * </pre>
         *
         * <code>string pass_video = 12;</code>
         */
        public com.google.protobuf.ByteString
            getPassVideoBytes() {
          Object ref = passVideo_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (String) ref);
            passVideo_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <pre>
         * 通行视频url
         * </pre>
         *
         * <code>string pass_video = 12;</code>
         */
        public Builder setPassVideo(
            String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          passVideo_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         * 通行视频url
         * </pre>
         *
         * <code>string pass_video = 12;</code>
         */
        public Builder clearPassVideo() {
          
          passVideo_ = getDefaultInstance().getPassVideo();
          onChanged();
          return this;
        }
        /**
         * <pre>
         * 通行视频url
         * </pre>
         *
         * <code>string pass_video = 12;</code>
         */
        public Builder setPassVideoBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          passVideo_ = value;
          onChanged();
          return this;
        }

        private Object reserve_ = "";
        /**
         * <pre>
         * 预留字段，用于存储通行记录的特定信息 JsonString  例如二维码通行时带有二维码特定自定义信息 {"qrCustomInfo":"xxxx"}
         * </pre>
         *
         * <code>string reserve = 13;</code>
         */
        public String getReserve() {
          Object ref = reserve_;
          if (!(ref instanceof String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            reserve_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        /**
         * <pre>
         * 预留字段，用于存储通行记录的特定信息 JsonString  例如二维码通行时带有二维码特定自定义信息 {"qrCustomInfo":"xxxx"}
         * </pre>
         *
         * <code>string reserve = 13;</code>
         */
        public com.google.protobuf.ByteString
            getReserveBytes() {
          Object ref = reserve_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (String) ref);
            reserve_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <pre>
         * 预留字段，用于存储通行记录的特定信息 JsonString  例如二维码通行时带有二维码特定自定义信息 {"qrCustomInfo":"xxxx"}
         * </pre>
         *
         * <code>string reserve = 13;</code>
         */
        public Builder setReserve(
            String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          reserve_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         * 预留字段，用于存储通行记录的特定信息 JsonString  例如二维码通行时带有二维码特定自定义信息 {"qrCustomInfo":"xxxx"}
         * </pre>
         *
         * <code>string reserve = 13;</code>
         */
        public Builder clearReserve() {
          
          reserve_ = getDefaultInstance().getReserve();
          onChanged();
          return this;
        }
        /**
         * <pre>
         * 预留字段，用于存储通行记录的特定信息 JsonString  例如二维码通行时带有二维码特定自定义信息 {"qrCustomInfo":"xxxx"}
         * </pre>
         *
         * <code>string reserve = 13;</code>
         */
        public Builder setReserveBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          reserve_ = value;
          onChanged();
          return this;
        }
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFieldsProto3(unknownFields);
        }

        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:TslIotProto.TSLIOTUploadPassLogRequest.TSLIOTPassLog)
      }

      // @@protoc_insertion_point(class_scope:TslIotProto.TSLIOTUploadPassLogRequest.TSLIOTPassLog)
      private static final TSLIOTPassLog DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new TSLIOTPassLog();
      }

      public static TSLIOTPassLog getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<TSLIOTPassLog>
          PARSER = new com.google.protobuf.AbstractParser<TSLIOTPassLog>() {
        public TSLIOTPassLog parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new TSLIOTPassLog(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<TSLIOTPassLog> parser() {
        return PARSER;
      }

      @Override
      public com.google.protobuf.Parser<TSLIOTPassLog> getParserForType() {
        return PARSER;
      }

      public TSLIOTPassLog getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int PASS_LOGS_FIELD_NUMBER = 1;
    private java.util.List<TSLIOTPassLog> passLogs_;
    /**
     * <pre>
     * 开门日志
     * </pre>
     *
     * <code>repeated .TslIotProto.TSLIOTUploadPassLogRequest.TSLIOTPassLog pass_logs = 1;</code>
     */
    public java.util.List<TSLIOTPassLog> getPassLogsList() {
      return passLogs_;
    }
    /**
     * <pre>
     * 开门日志
     * </pre>
     *
     * <code>repeated .TslIotProto.TSLIOTUploadPassLogRequest.TSLIOTPassLog pass_logs = 1;</code>
     */
    public java.util.List<? extends TSLIOTPassLogOrBuilder>
        getPassLogsOrBuilderList() {
      return passLogs_;
    }
    /**
     * <pre>
     * 开门日志
     * </pre>
     *
     * <code>repeated .TslIotProto.TSLIOTUploadPassLogRequest.TSLIOTPassLog pass_logs = 1;</code>
     */
    public int getPassLogsCount() {
      return passLogs_.size();
    }
    /**
     * <pre>
     * 开门日志
     * </pre>
     *
     * <code>repeated .TslIotProto.TSLIOTUploadPassLogRequest.TSLIOTPassLog pass_logs = 1;</code>
     */
    public TSLIOTPassLog getPassLogs(int index) {
      return passLogs_.get(index);
    }
    /**
     * <pre>
     * 开门日志
     * </pre>
     *
     * <code>repeated .TslIotProto.TSLIOTUploadPassLogRequest.TSLIOTPassLog pass_logs = 1;</code>
     */
    public TSLIOTPassLogOrBuilder getPassLogsOrBuilder(
        int index) {
      return passLogs_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < passLogs_.size(); i++) {
        output.writeMessage(1, passLogs_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < passLogs_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, passLogs_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof TSLIOTUploadPassLogRequest)) {
        return super.equals(obj);
      }
      TSLIOTUploadPassLogRequest other = (TSLIOTUploadPassLogRequest) obj;

      boolean result = true;
      result = result && getPassLogsList()
          .equals(other.getPassLogsList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getPassLogsCount() > 0) {
        hash = (37 * hash) + PASS_LOGS_FIELD_NUMBER;
        hash = (53 * hash) + getPassLogsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static TSLIOTUploadPassLogRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TSLIOTUploadPassLogRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TSLIOTUploadPassLogRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TSLIOTUploadPassLogRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TSLIOTUploadPassLogRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TSLIOTUploadPassLogRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TSLIOTUploadPassLogRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static TSLIOTUploadPassLogRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static TSLIOTUploadPassLogRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static TSLIOTUploadPassLogRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static TSLIOTUploadPassLogRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static TSLIOTUploadPassLogRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(TSLIOTUploadPassLogRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 通行日志
     * </pre>
     *
     * Protobuf type {@code TslIotProto.TSLIOTUploadPassLogRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TslIotProto.TSLIOTUploadPassLogRequest)
        TSLIOTUploadPassLogRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return TSLIOTBusinessLog.internal_static_TslIotProto_TSLIOTUploadPassLogRequest_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return TSLIOTBusinessLog.internal_static_TslIotProto_TSLIOTUploadPassLogRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                TSLIOTUploadPassLogRequest.class, Builder.class);
      }

      // Construct using com.terminus.iotextension.mqtt.protobuf.TSLIOTBusinessLog.TSLIOTUploadPassLogRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getPassLogsFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (passLogsBuilder_ == null) {
          passLogs_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          passLogsBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return TSLIOTBusinessLog.internal_static_TslIotProto_TSLIOTUploadPassLogRequest_descriptor;
      }

      public TSLIOTUploadPassLogRequest getDefaultInstanceForType() {
        return TSLIOTUploadPassLogRequest.getDefaultInstance();
      }

      public TSLIOTUploadPassLogRequest build() {
        TSLIOTUploadPassLogRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public TSLIOTUploadPassLogRequest buildPartial() {
        TSLIOTUploadPassLogRequest result = new TSLIOTUploadPassLogRequest(this);
        int from_bitField0_ = bitField0_;
        if (passLogsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            passLogs_ = java.util.Collections.unmodifiableList(passLogs_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.passLogs_ = passLogs_;
        } else {
          result.passLogs_ = passLogsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof TSLIOTUploadPassLogRequest) {
          return mergeFrom((TSLIOTUploadPassLogRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(TSLIOTUploadPassLogRequest other) {
        if (other == TSLIOTUploadPassLogRequest.getDefaultInstance()) return this;
        if (passLogsBuilder_ == null) {
          if (!other.passLogs_.isEmpty()) {
            if (passLogs_.isEmpty()) {
              passLogs_ = other.passLogs_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensurePassLogsIsMutable();
              passLogs_.addAll(other.passLogs_);
            }
            onChanged();
          }
        } else {
          if (!other.passLogs_.isEmpty()) {
            if (passLogsBuilder_.isEmpty()) {
              passLogsBuilder_.dispose();
              passLogsBuilder_ = null;
              passLogs_ = other.passLogs_;
              bitField0_ = (bitField0_ & ~0x00000001);
              passLogsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getPassLogsFieldBuilder() : null;
            } else {
              passLogsBuilder_.addAllMessages(other.passLogs_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        TSLIOTUploadPassLogRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (TSLIOTUploadPassLogRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<TSLIOTPassLog> passLogs_ =
        java.util.Collections.emptyList();
      private void ensurePassLogsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          passLogs_ = new java.util.ArrayList<TSLIOTPassLog>(passLogs_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          TSLIOTPassLog, TSLIOTPassLog.Builder, TSLIOTPassLogOrBuilder> passLogsBuilder_;

      /**
       * <pre>
       * 开门日志
       * </pre>
       *
       * <code>repeated .TslIotProto.TSLIOTUploadPassLogRequest.TSLIOTPassLog pass_logs = 1;</code>
       */
      public java.util.List<TSLIOTPassLog> getPassLogsList() {
        if (passLogsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(passLogs_);
        } else {
          return passLogsBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       * 开门日志
       * </pre>
       *
       * <code>repeated .TslIotProto.TSLIOTUploadPassLogRequest.TSLIOTPassLog pass_logs = 1;</code>
       */
      public int getPassLogsCount() {
        if (passLogsBuilder_ == null) {
          return passLogs_.size();
        } else {
          return passLogsBuilder_.getCount();
        }
      }
      /**
       * <pre>
       * 开门日志
       * </pre>
       *
       * <code>repeated .TslIotProto.TSLIOTUploadPassLogRequest.TSLIOTPassLog pass_logs = 1;</code>
       */
      public TSLIOTPassLog getPassLogs(int index) {
        if (passLogsBuilder_ == null) {
          return passLogs_.get(index);
        } else {
          return passLogsBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       * 开门日志
       * </pre>
       *
       * <code>repeated .TslIotProto.TSLIOTUploadPassLogRequest.TSLIOTPassLog pass_logs = 1;</code>
       */
      public Builder setPassLogs(
          int index, TSLIOTPassLog value) {
        if (passLogsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePassLogsIsMutable();
          passLogs_.set(index, value);
          onChanged();
        } else {
          passLogsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * 开门日志
       * </pre>
       *
       * <code>repeated .TslIotProto.TSLIOTUploadPassLogRequest.TSLIOTPassLog pass_logs = 1;</code>
       */
      public Builder setPassLogs(
          int index, TSLIOTPassLog.Builder builderForValue) {
        if (passLogsBuilder_ == null) {
          ensurePassLogsIsMutable();
          passLogs_.set(index, builderForValue.build());
          onChanged();
        } else {
          passLogsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 开门日志
       * </pre>
       *
       * <code>repeated .TslIotProto.TSLIOTUploadPassLogRequest.TSLIOTPassLog pass_logs = 1;</code>
       */
      public Builder addPassLogs(TSLIOTPassLog value) {
        if (passLogsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePassLogsIsMutable();
          passLogs_.add(value);
          onChanged();
        } else {
          passLogsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       * 开门日志
       * </pre>
       *
       * <code>repeated .TslIotProto.TSLIOTUploadPassLogRequest.TSLIOTPassLog pass_logs = 1;</code>
       */
      public Builder addPassLogs(
          int index, TSLIOTPassLog value) {
        if (passLogsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePassLogsIsMutable();
          passLogs_.add(index, value);
          onChanged();
        } else {
          passLogsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * 开门日志
       * </pre>
       *
       * <code>repeated .TslIotProto.TSLIOTUploadPassLogRequest.TSLIOTPassLog pass_logs = 1;</code>
       */
      public Builder addPassLogs(
          TSLIOTPassLog.Builder builderForValue) {
        if (passLogsBuilder_ == null) {
          ensurePassLogsIsMutable();
          passLogs_.add(builderForValue.build());
          onChanged();
        } else {
          passLogsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 开门日志
       * </pre>
       *
       * <code>repeated .TslIotProto.TSLIOTUploadPassLogRequest.TSLIOTPassLog pass_logs = 1;</code>
       */
      public Builder addPassLogs(
          int index, TSLIOTPassLog.Builder builderForValue) {
        if (passLogsBuilder_ == null) {
          ensurePassLogsIsMutable();
          passLogs_.add(index, builderForValue.build());
          onChanged();
        } else {
          passLogsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 开门日志
       * </pre>
       *
       * <code>repeated .TslIotProto.TSLIOTUploadPassLogRequest.TSLIOTPassLog pass_logs = 1;</code>
       */
      public Builder addAllPassLogs(
          Iterable<? extends TSLIOTPassLog> values) {
        if (passLogsBuilder_ == null) {
          ensurePassLogsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, passLogs_);
          onChanged();
        } else {
          passLogsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       * 开门日志
       * </pre>
       *
       * <code>repeated .TslIotProto.TSLIOTUploadPassLogRequest.TSLIOTPassLog pass_logs = 1;</code>
       */
      public Builder clearPassLogs() {
        if (passLogsBuilder_ == null) {
          passLogs_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          passLogsBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * 开门日志
       * </pre>
       *
       * <code>repeated .TslIotProto.TSLIOTUploadPassLogRequest.TSLIOTPassLog pass_logs = 1;</code>
       */
      public Builder removePassLogs(int index) {
        if (passLogsBuilder_ == null) {
          ensurePassLogsIsMutable();
          passLogs_.remove(index);
          onChanged();
        } else {
          passLogsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       * 开门日志
       * </pre>
       *
       * <code>repeated .TslIotProto.TSLIOTUploadPassLogRequest.TSLIOTPassLog pass_logs = 1;</code>
       */
      public TSLIOTPassLog.Builder getPassLogsBuilder(
          int index) {
        return getPassLogsFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       * 开门日志
       * </pre>
       *
       * <code>repeated .TslIotProto.TSLIOTUploadPassLogRequest.TSLIOTPassLog pass_logs = 1;</code>
       */
      public TSLIOTPassLogOrBuilder getPassLogsOrBuilder(
          int index) {
        if (passLogsBuilder_ == null) {
          return passLogs_.get(index);  } else {
          return passLogsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       * 开门日志
       * </pre>
       *
       * <code>repeated .TslIotProto.TSLIOTUploadPassLogRequest.TSLIOTPassLog pass_logs = 1;</code>
       */
      public java.util.List<? extends TSLIOTPassLogOrBuilder>
           getPassLogsOrBuilderList() {
        if (passLogsBuilder_ != null) {
          return passLogsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(passLogs_);
        }
      }
      /**
       * <pre>
       * 开门日志
       * </pre>
       *
       * <code>repeated .TslIotProto.TSLIOTUploadPassLogRequest.TSLIOTPassLog pass_logs = 1;</code>
       */
      public TSLIOTPassLog.Builder addPassLogsBuilder() {
        return getPassLogsFieldBuilder().addBuilder(
            TSLIOTPassLog.getDefaultInstance());
      }
      /**
       * <pre>
       * 开门日志
       * </pre>
       *
       * <code>repeated .TslIotProto.TSLIOTUploadPassLogRequest.TSLIOTPassLog pass_logs = 1;</code>
       */
      public TSLIOTPassLog.Builder addPassLogsBuilder(
          int index) {
        return getPassLogsFieldBuilder().addBuilder(
            index, TSLIOTPassLog.getDefaultInstance());
      }
      /**
       * <pre>
       * 开门日志
       * </pre>
       *
       * <code>repeated .TslIotProto.TSLIOTUploadPassLogRequest.TSLIOTPassLog pass_logs = 1;</code>
       */
      public java.util.List<TSLIOTPassLog.Builder>
           getPassLogsBuilderList() {
        return getPassLogsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          TSLIOTPassLog, TSLIOTPassLog.Builder, TSLIOTPassLogOrBuilder>
          getPassLogsFieldBuilder() {
        if (passLogsBuilder_ == null) {
          passLogsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              TSLIOTPassLog, TSLIOTPassLog.Builder, TSLIOTPassLogOrBuilder>(
                  passLogs_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          passLogs_ = null;
        }
        return passLogsBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:TslIotProto.TSLIOTUploadPassLogRequest)
    }

    // @@protoc_insertion_point(class_scope:TslIotProto.TSLIOTUploadPassLogRequest)
    private static final TSLIOTUploadPassLogRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new TSLIOTUploadPassLogRequest();
    }

    public static TSLIOTUploadPassLogRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TSLIOTUploadPassLogRequest>
        PARSER = new com.google.protobuf.AbstractParser<TSLIOTUploadPassLogRequest>() {
      public TSLIOTUploadPassLogRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TSLIOTUploadPassLogRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TSLIOTUploadPassLogRequest> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<TSLIOTUploadPassLogRequest> getParserForType() {
      return PARSER;
    }

    public TSLIOTUploadPassLogRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TslIotProto_TSLIOTUploadPassLogRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TslIotProto_TSLIOTUploadPassLogRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TslIotProto_TSLIOTUploadPassLogRequest_TSLIOTPassLog_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TslIotProto_TSLIOTUploadPassLogRequest_TSLIOTPassLog_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\027TSLIOTBusinessLog.proto\022\013TslIotProto\"\346" +
      "\002\n\032TSLIOTUploadPassLogRequest\022H\n\tpass_lo" +
      "gs\030\001 \003(\01325.TslIotProto.TSLIOTUploadPassL" +
      "ogRequest.TSLIOTPassLog\032\375\001\n\rTSLIOTPassLo" +
      "g\022\016\n\006dev_id\030\001 \001(\t\022\021\n\tperson_id\030\002 \001(\003\022\017\n\007" +
      "feature\030\003 \001(\t\022\023\n\013person_type\030\004 \001(\t\022\021\n\tdi" +
      "rection\030\005 \001(\005\022\014\n\004time\030\006 \001(\003\022\023\n\013open_resu" +
      "lt\030\007 \001(\005\022\022\n\ndev_status\030\010 \001(\005\022\021\n\topen_typ" +
      "e\030\t \001(\005\022\017\n\007card_no\030\n \001(\t\022\020\n\010pass_img\030\013 \001" +
      "(\t\022\022\n\npass_video\030\014 \001(\t\022\017\n\007reserve\030\r \001(\tB" +
      ")\n\'com.terminus.iotextension.mqtt.protob" +
      "ufb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_TslIotProto_TSLIOTUploadPassLogRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_TslIotProto_TSLIOTUploadPassLogRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TslIotProto_TSLIOTUploadPassLogRequest_descriptor,
        new String[] { "PassLogs", });
    internal_static_TslIotProto_TSLIOTUploadPassLogRequest_TSLIOTPassLog_descriptor =
      internal_static_TslIotProto_TSLIOTUploadPassLogRequest_descriptor.getNestedTypes().get(0);
    internal_static_TslIotProto_TSLIOTUploadPassLogRequest_TSLIOTPassLog_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TslIotProto_TSLIOTUploadPassLogRequest_TSLIOTPassLog_descriptor,
        new String[] { "DevId", "PersonId", "Feature", "PersonType", "Direction", "Time", "OpenResult", "DevStatus", "OpenType", "CardNo", "PassImg", "PassVideo", "Reserve", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
